### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by DreamPWJ** [poad/appstore-connect-jwt-generator-cli#583]
at file:///C:/Users/Lenovo/AppData/Roaming/npm/node_modules/appstore-connect-jwt-generator-cli/bin/cli.js:2:1
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by poad** [comment]
@DreamPWJ
Thanks for the report. I will look into the cause of this problem.

**Comment by poad** [comment]
@DreamPWJ 
Fix the this problems.
Please update the version to 1.0.2.
